{% set name = "deepmerge" %}
{% set version = "2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deepmerge-{{ version }}.tar.gz
  sha256: 5c3d86081fbebd04dd5de03626a0607b809a98fb6ccba5770b62466fe940ff20

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - deepmerge
    - deepmerge.strategy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://deepmerge.readthedocs.io/en/latest/
  summary: a toolset to deeply merge python dictionaries.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
