{% set name = "deepmerge" %}
{% set version = "3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/deepmerge-{{ version }}.tar.gz
  sha256: 14ed69f063de64b7743985c732ccff5d6c34ff4560946e7fbfd99086b853b9ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - deepmerge
    - deepmerge.strategy
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: http://deepmerge.readthedocs.io/en/latest/
  summary: a toolset to deeply merge python dictionaries.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
